version: "3.9"

services:
  api:
    depends_on:
      - postgresql
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    # env_file:
    # - .env.development
    # Run a command against the development stage of the image
    # command: 
    command: npx npx prisma migrate dev &&  npm run start:dev 

    ports:
      - 3001:3001
  postgresql:
    image: postgres:13
    container_name: dc-postgres
    restart: always
    env_file:
    - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DATABASE_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRESS_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # expose:
    #   - 5432
volumes:
  postgres_data:


